Repository PureSwift/Bluetooth, pull requests merged in 2018-06, with the labels that each got.

#44 Add GAP Data types
  Sources/BluetoothUUID.swift
  Sources/ClassOfDevice.swift
  Sources/CompanyIdentifierExtension.swift
  Sources/Data.swift
  Sources/DefinedUUIDExtension.swift
  Sources/GAPAppearance.swift
  Sources/GenericAccessProfile.swift
  Sources/Hexadecimal.swift
  Sources/LowEnergyFeature.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/BluetoothUUIDTests.swift
  Tests/BluetoothTests/CompanyIdentifierTests.swift
  Tests/BluetoothTests/DarwinTests.swift
  Tests/BluetoothTests/DefinedUUIDTests.swift
  Tests/BluetoothTests/GAPTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
  Xcode/Bluetooth.xcodeproj/xcshareddata/xcbaselines/6EE84DC01CAF5C7C00A40C4D.xcbaseline/E272A968-C86F-4169-956E-E6220948798B.plist
  Xcode/Bluetooth.xcodeproj/xcshareddata/xcbaselines/6EE84DC01CAF5C7C00A40C4D.xcbaseline/Info.plist
Labels: enhancement, good first issue

#60 Added code generation for `UnitIdentifier`
  Sources/UnitIdentifier.swift
  Sources/UnitIdentifierExtension.swift
  Tests/BluetoothTests/DarwinTests.swift
  Tests/BluetoothTests/UnitIdentifierTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#76 Added GATT Body Sensor Location
  Sources/GATTBodySensorLocation.swift
  Sources/Integer.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#81 Added GATT Central Address Resolution Characteristic
  Sources/GATTCentralAddressResolution.swift
  Sources/Integer.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#77 Added GATT Boot Keyboard Input Report Characteristic
  Sources/GATTBootKeyboardInputReport.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#80 Added GATT Boot Mouse Input Report Characteristic
  Sources/GATTBootKeyboardInputReport.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#78 Added GATT Boot Keyboard Output Report Characteristic
  Sources/GATTBootKeyboardOutputReport.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#84 Added GATT Device Information Characteristics
  Sources/GATTFirmwareRevisionString.swift
  Sources/GATTManufacturerNameString.swift
  Sources/GATTModelNumber.swift
  Sources/GATTPnPID.swift
  Sources/GATTSoftwareRevisionString.swift
  Sources/GATTSystemID.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#89 Fixed `GATTSystemID` and added `UInt40 and `UInt24`
  Sources/GATTSystemID.swift
  Sources/UInt24.swift
  Sources/UInt40.swift
  Tests/BluetoothTests/GATTCharacteristicTests.swift
  Tests/BluetoothTests/UInt24Tests.swift
  Tests/BluetoothTests/UInt40Tests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#90 Fixed Travis CI
  .travis.yml
Labels: bug
