Repository PureSwift/Bluetooth, pull requests merged in 2018-04, with the labels that each got.

#22 #13 Added `HCICommand.name`
  Sources/HCI.swift
  Sources/HCICommand.swift
  Sources/HCIError.swift
  Sources/HCIEvent.swift
  Sources/HCIGeneralEvent.swift
  Sources/HostControllerBasebandCommand.swift
  Sources/InformationalParametersCommand.swift
  Sources/LinkControlCommand.swift
  Sources/LinkPolicyCommand.swift
  Sources/LowEnergyCommand.swift
  Sources/LowEnergyEvent.swift
  Sources/StatusParametersCommand.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/HostController.swift
Labels: enhancement

#26 Updated BluetoothUUID
  Sources/Address.swift
  Sources/BluetoothUUID.swift
  Sources/ByteSwap.swift
  Sources/ByteValue.swift
  Sources/GATTClient.swift
  Sources/GATTDatabase.swift
  Sources/GATTServer.swift
  Sources/UInt128.swift
  Sources/UUID.swift
  Sources/iBeacon.swift
  Tests/BluetoothTests/AddressTests.swift
  Tests/BluetoothTests/AttributeProtocolTests.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/BluetoothUUIDTests.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/UInt128Tests.swift
  Tests/BluetoothTests/UUIDTests.swift
  Tests/BluetoothTests/XCTest.swift
  Tests/BluetoothTests/iBeaconTests.swift
  Tests/LinuxMain.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
  Xcode/Bluetooth.xcodeproj/xcshareddata/xcbaselines/6EE84DC01CAF5C7C00A40C4D.xcbaseline/E272A968-C86F-4169-956E-E6220948798B.plist
  Xcode/Bluetooth.xcodeproj/xcshareddata/xcschemes/Bluetooth-macOS.xcscheme
Labels: enhancement

#29 Updated unit tests
  Sources/BluetoothUUID.swift
  Sources/CompanyIdentifier.swift
  Sources/HCICommandTimeout.swift
  Sources/iBeacon.swift
  Tests/BluetoothTests/AttributeProtocolTests.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/BluetoothUUIDTests.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/iBeaconTests.swift
Labels: enhancement

#30 Added GATT and ATT PDU Unit Tests
  Assets/ATTExchangeMTU.png
  Sources/ATT.swift
  Sources/ATTConnection.swift
  Sources/ATTMaximumTransmissionUnit.swift
  Sources/ATTProtocolDataUnit.swift
  Sources/GATTClient.swift
  Sources/GATTDatabase.swift
  Sources/GATTServer.swift
  Sources/LowEnergyCommandParameter.swift
  Tests/BluetoothTests/AttributeProtocolTests.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/GATTTests.swift
  Tests/BluetoothTests/L2CAPSocket.swift
  Tests/BluetoothTests/iBeaconTests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#21 [#3] Implement HCI LE Commands
  .swiftlint.yml
  Sources/ATT.swift
  Sources/Address.swift
  Sources/BluetoothHostController.swift
  Sources/GATT.swift
  Sources/HCI.swift
  Sources/HCIGeneralEvent.swift
  Sources/HCIGeneralEventParameter.swift
  Sources/HCIPacketHeader.swift
  Sources/HostControllerLocalName.swift
  Sources/InformationalCommand.swift
  Sources/InformationalCommandParameter.swift
  Sources/InformationalParameters.swift
  Sources/InformationalParametersCommand.swift
  Sources/LowEnergyAdvertising.swift
  Sources/LowEnergyCommand.swift
  Sources/LowEnergyCommandParameter.swift
  Sources/LowEnergyConnection.swift
  Sources/LowEnergyEncryption.swift
  Sources/LowEnergyEvent.swift
  Sources/LowEnergyEventParameter.swift
  Sources/LowEnergyFeature.swift
  Sources/LowEnergyFeaturesCommands.swift
  Sources/LowEnergyLongTermKeyRequest.swift
  Sources/LowEnergyPhyCommands.swift
  Sources/LowEnergyRandomAddress.swift
  Sources/LowEnergyResolvingList.swift
  Sources/LowEnergyState.swift
  Sources/LowEnergyTestCommands.swift
  Sources/LowEnergyWhiteList.swift
  Sources/POSIXError.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/HostController.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement

#34 [#3] Implement all HCI LE Commands
  .swiftlint.yml
  Sources/LowEnergyAdvertising.swift
  Sources/LowEnergyCommand.swift
  Sources/LowEnergyCommandParameter.swift
  Sources/LowEnergyConnection.swift
  Sources/LowEnergyEvent.swift
  Sources/LowEnergyEventParameter.swift
  Sources/LowEnergyFeaturesCommands.swift
  Sources/LowEnergyScan.swift
  Sources/UInt256.swift
  Sources/UInt512.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/UInt256Tests.swift
  Tests/BluetoothTests/UInt512Tests.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement, good first issue

#36 Added GAP Data Types
  .swiftlint.yml
  Sources/DefinedUUIDExtension.swift
  Sources/GenericAccessProfile.swift
  Sources/LowEnergyAdvertising.swift
  Sources/LowEnergyAdvertisingData.swift
  Sources/LowEnergyCommandParameter.swift
  Sources/LowEnergyScan.swift
  Sources/iBeacon.swift
  Tests/BluetoothTests/BluetoothTests.swift
  Tests/BluetoothTests/BluetoothUUIDTests.swift
  Tests/BluetoothTests/DefinedUUIDTests.swift
  Tests/BluetoothTests/GAPTests.swift
  Tests/BluetoothTests/HCITests.swift
  Tests/BluetoothTests/iBeaconTests.swift
  Tests/LinuxMain.swift
  Xcode/Bluetooth.xcodeproj/project.pbxproj
Labels: enhancement, good first issue, help wanted
